name: Releases

on: 
  push:
    tags:
    - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@master
    - name: Set up Go
      uses: actions/setup-go@v4
      with: 
        go-version: '1.20'
    - name: Go Build
      run: CGO_ENABLED=1 go build -v -a -ldflags '-extldflags "-static"' ./network_detail.go
    - name: Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "network_detail,readme.md"
        allowUpdates: true
    
